### ISSUE TITLE
Bing Maps Dev Center 已经不为新用户提供api了

### ISSUE THREAD

**Issue by D2550** [Yorkian/knock#1]
这是您第一次使用 xxx 登录 Bing Maps Dev Center 。Bing Maps for Enterprise 已被弃用并将退役。企业账户客户可以继续使用 Bing Maps for Enterprise 服务，直到 2028 年 6 月 30 日。现有免费（基本）账户客户可以继续使用 Bing Maps for Enterprise 服务，直到 2025 年 6 月 30 日。

**Comment by yeyuchen198** [comment]
> 这是您第一次使用 xxx 登录 Bing Maps Dev Center 。Bing Maps for Enterprise 已被弃用并将退役。企业账户客户可以继续使用 Bing Maps for Enterprise 服务，直到 2028 年 6 月 30 日。现有免费（基本）账户客户可以继续使用 Bing Maps for Enterprise 服务，直到 2025 年 6 月 30 日。

改为Azure了，感觉要付费了，从25年7月1号开始

**Comment by Yorkian** [comment]
我尝试找一下平替或其他方案

**Comment by Yorkian** [comment]
> 这是您第一次使用 xxx 登录 Bing Maps Dev Center 。Bing Maps for Enterprise 已被弃用并将退役。企业账户客户可以继续使用 Bing Maps for Enterprise 服务，直到 2028 年 6 月 30 日。现有免费（基本）账户客户可以继续使用 Bing Maps for Enterprise 服务，直到 2025 年 6 月 30 日。

已经更新了后端逻辑，不需要Bing Map服务也可以正常使用。
